@host = http://localhost:5263

GET {{host}}/api/backlogitems
Accept: application/json

### Create and item
POST {{host}}/api/backlogitems
Content-Type: application/json

{
  "title": "New Spyro",
  "category": 2
}

### Update an item (paste a real id from a GET/POST response)
PUT {{host}}/api/backlogitems/6a56ce85-e418-4751-8eab-730a422539e8
Content-Type: application/json

{
  "status": 1,
  "rating": 8.5,
  "note": "Halfway through"
}

### Delete an item (paste a real id)
DELETE  {{host}}/api/backlogitems/f6262f92-05f9-4a4d-b5c3-5e2d20e3a89a
Content-Type: application/json
