// <auto-generated />
using System;
using Backlog.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backlog.Api.Migrations
{
    [DbContext(typeof(BacklogDbContext))]
    partial class BacklogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backlog.Api.Models.BacklogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BacklogItems");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BacklogItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backlog.Api.Models.Book", b =>
                {
                    b.HasBaseType("Backlog.Api.Models.BacklogItem");

                    b.Property<int?>("TotalPages")
                        .HasColumnType("integer");

                    b.Property<int?>("YearReleased")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Book");
                });

            modelBuilder.Entity("Backlog.Api.Models.Movie", b =>
                {
                    b.HasBaseType("Backlog.Api.Models.BacklogItem");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("YearReleased")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("Backlog.Api.Models.Show", b =>
                {
                    b.HasBaseType("Backlog.Api.Models.BacklogItem");

                    b.Property<int?>("Seasons")
                        .HasColumnType("integer");

                    b.Property<int?>("YearReleased")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Show");
                });

            modelBuilder.Entity("Backlog.Api.Models.Vacation", b =>
                {
                    b.HasBaseType("Backlog.Api.Models.BacklogItem");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("numeric");

                    b.Property<int?>("HowManyDays")
                        .HasColumnType("integer");

                    b.Property<int?>("YearReleased")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Vacation");
                });

            modelBuilder.Entity("Backlog.Api.Models.VideoGame", b =>
                {
                    b.HasBaseType("Backlog.Api.Models.BacklogItem");

                    b.Property<int?>("HowLongToBeat")
                        .HasColumnType("integer");

                    b.Property<int?>("YearReleased")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("VideoGame");
                });
#pragma warning restore 612, 618
        }
    }
}
